// shared/constants/errorCodes.js
module.exports = {
  // Authentication errors
  AUTH: {
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    TOKEN_INVALID: "TOKEN_INVALID",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  },

  // Validation errors
  VALIDATION: {
    REQUIRED_FIELD: "REQUIRED_FIELD",
    INVALID_FORMAT: "INVALID_FORMAT",
    INVALID_EMAIL: "INVALID_EMAIL",
    INVALID_PHONE: "INVALID_PHONE",
    PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
    INVALID_DATE: "INVALID_DATE",
    FILE_TOO_LARGE: "FILE_TOO_LARGE",
    INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  },

  // Database errors
  DATABASE: {
    CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",
    DUPLICATE_KEY: "DUPLICATE_KEY_ERROR",
    NOT_FOUND: "NOT_FOUND",
    SAVE_ERROR: "SAVE_ERROR",
    UPDATE_ERROR: "UPDATE_ERROR",
    DELETE_ERROR: "DELETE_ERROR",
  },

  // External service errors
  EXTERNAL: {
    SMS_SEND_FAILED: "SMS_SEND_FAILED",
    FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
    OCR_FAILED: "OCR_PROCESSING_FAILED",
    AI_PROCESSING_FAILED: "AI_PROCESSING_FAILED",
  },

  // Rate limiting
  RATE_LIMIT: {
    TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
    TOO_MANY_LOGIN_ATTEMPTS: "TOO_MANY_LOGIN_ATTEMPTS",
  },

  // General errors
  GENERAL: {
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    BAD_REQUEST: "BAD_REQUEST",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  },
};
